### ISSUE TITLE
Collection summaries should be updated by ingestor

### ISSUE THREAD

**Issue by anayeaye** [NASA-IMPACT/veda-stac-ingestor#25]
# What
Collection summaries should be added to collections with default COG assets by default. The [veda-stac-ingestor load_ingo_pgstac method](https://github.com/NASA-IMPACT/veda-stac-ingestor/blob/main/api/src/ingestor.py#L99) should be adding the summary but this is not happening automatically. 

This may be a deployment task not a code change.

# Why
Collection summaries are required to view datasets in the dashboard exploration map. Currently this has to be done by manually connecting to the database and executing the user defined function.

# AC
- [ ] Collection summaries are added to collections with *default COG assets* (no manual step required)
- [ ] Updated collection extents are in UTC (see bug described [here](https://github.com/NASA-IMPACT/veda-data-pipelines/issues/228#issuecomment-1317426027)

**Comment by moradology** [comment]
Closing this issue as it appears to be completed already: https://github.com/NASA-IMPACT/veda-stac-ingestor/pull/23
