### ISSUE TITLE
Trigger airflow dag with `/workflows-execution`

### ISSUE THREAD

**Issue by slesaad** [NASA-IMPACT/veda-stac-ingestor#32]
# Description

Currently the `/workflows-execution` endpoint triggers the step function workflow for discovery (and consequently ingestion). Since we're moving our workflows from step functions to airflow dag, we need to update this behavior to trigger a dag instead.

Example of triggering an airflow dag: https://amarouane-ecs-cluster.snwg-impact.net/notebooks/work/netcdf_to_cog.ipynb

# Acceptance Criteria
- [ ] calling `/workflows-execution` with the dataset definition trigger the discovery/ingestion airflow dag

**Comment by jpolchlo** [comment]
@moradology Trying to pick up this task, but the example link posted by @slesaad gives a 404, and I can't find the branch you mentioned; `./scripts/item.py` does not appear to define an airflow dag.  Can you point to a different, working Airflow DAG?

**Comment by moradology** [comment]
Here's the `item.py` file which triggers an airflow dag: https://github.com/NASA-IMPACT/veda-data-pipelines/blob/feature/veda-mwaa/scripts/item.py

The dags are down as I'm currently locked in a death-struggle with Terraform, but I will let you know once it is up
