### ISSUE TITLE
More informative pydantic validation errors

### ISSUE THREAD

**Issue by emileten** [NASA-IMPACT/veda-stac-ingestor#54]
I have been trying to use [to use the `/collections` endpoint](https://github.com/NASA-IMPACT/veda-stac-ingestor/blob/0558c10a12a25918a499a671d7de164ad2611f28/api/src/main.py#L111) for the MAAP project. Specifically, I was [sending a POST request](https://github.com/MAAP-Project/veda-data-pipelines/blob/8a33712d267406cadf48c7463852e5a9a33d002a/scripts/collection.py#L45) with [this collection json](https://github.com/MAAP-Project/veda-data-pipelines/blob/main/data/collections/AfriSAR_UAVSAR_Coreg_SLC.json). This [was returning me a `422 client error`](https://github.com/MAAP-Project/veda-data-pipelines/pull/11#issuecomment-1481976582).

Looking for logs in the AWS management console, in particular [in the `api-handler` lambda function](https://github.com/NASA-IMPACT/veda-stac-ingestor/blob/0558c10a12a25918a499a671d7de164ad2611f28/cdk/stack.py#L243), which is where this collection ingestion is happening, I could see my requests but no error message. It took @abarciauskas-bgse and me quite a lot of debugging and running the server locally in order to realize that the problem was simply that our collection json [wasn't complying](https://github.com/NASA-IMPACT/veda-stac-ingestor/blob/0558c10a12a25918a499a671d7de164ad2611f28/api/src/main.py#L117) to the `schemas.DashboardCollection` model, that requires both explicitly an `is_periodic` key, and implicitly also a `links` key (because it inherits from `stac_pydantic.collection.Collection` itself inheriting [from `stac_pydantic.catalog.Catalog`](https://github.com/stac-utils/stac-pydantic/blob/86f7303efce7d16261d37c0d8ee333f6cc22e7ed/stac_pydantic/catalog.py#L9)).

This is an input validation error, and ideally, information about it should be provided on the user side. I haven't thought yet about what the right way to handle this should be. 

Links to https://github.com/MAAP-Project/veda-data-pipelines/pull/11.

**Comment by j08lue** [comment]
Making the data submission flow more accessible to non-dev users is top of our agenda in VEDA. Including validation error details in the API response seems like an obvious thing to do.

**Comment by anayeaye** [comment]
this is related to but distinct from: #53 (linking because fixes implemented here may also support closing the earlier issue if the dashboard-specific logic is removed)

**Comment by emileten** [comment]
@ividito thanks ! Using a code identical [to this VEDA data pipelines method](https://github.com/NASA-IMPACT/veda-data-pipelines/blob/ac465e17e0bc2615754980482895f3ddedf21f2a/scripts/collection.py#L50) and trying to `post` the linked collection to the stac ingestor (happens with the MAAP deployment as well as a local deployment), I am [getting this error message (which does not have all these details)](https://github.com/MAAP-Project/veda-data-pipelines/pull/11#issuecomment-1481976582). Maybe it's due to the code I linked that doesn't display the error content entirely ?

**Comment by moradology** [comment]
@emileten Going through our backlog this morning, and I came across this but I'm not sure it describes the current reality. Given that changes were made on the pydantic models which were not providing validation clues, is this still an issue or should we close it?

**Comment by emileten** [comment]
@moradology we can close this. I realized after some time that the the problem was in my client code not retrieving the error message properly. Isayah's description of the behavior is accurate : 

> We currently return our [422 errors](https://github.com/NASA-IMPACT/veda-stac-ingestor> /blob/0558c10a12a25918a499a671d7de164ad2611f28/api/src/main.py#L254) with descriptions of the corresponding validation errors, although we don't do much to make these errors user-friendly.
